const fs=require('fs'),{JSDOM}=require('jsdom');
function setup(){const d=new JSDOM('<html lang="ru" data-theme="dark"><head></head><body><button id="radioBtn"></button></body></html>',{url:'https://example.com/',runScripts:'outside-only'}),w=d.window,audios=[];w.matchMedia=()=>({matches:false,addEventListener(){}});w.cancelAnimationFrame=jest.fn();w.Audio=class extends w.EventTarget{constructor(){super();this.currentTime=0;this.duration=3000;this.pause=jest.fn();this.load=jest.fn();audios.push(this);}play(){return Promise.resolve();}removeAttribute(k){if(k==='src')this.src='';}};w.eval(fs.readFileSync('src/js/radio-visualizer.js','utf8'));w.eval(fs.readFileSync('src/js/local-music-deck.js','utf8'));return {d,w,audios};}
const flush=async()=>{for(let i=0;i<8;i++)await Promise.resolve();};
test('MP3 is lazy and selected source uses same-origin audio, no YouTube',async()=>{const x=setup();expect(x.audios).toHaveLength(0);x.w.document.querySelector('[data-music-source=music]').click();await flush();expect(x.audios).toHaveLength(1);expect(x.audios[0].src).toBe('assets/audio/atmospheric-journey.mp3');expect(x.audios[0].loop).toBe(true);expect(x.w.RadioDeckBridge.state.local).toBe(true);expect(x.w.document.querySelector('iframe')).toBeNull();x.d.window.close();});
test('pause and resume preserve track position; seek and volume work',async()=>{const x=setup();x.w.RadioDeckBridge.select('personal');await flush();x.w.RadioDeckBridge.seek(125);expect(x.audios[0].currentTime).toBe(125);x.w.RadioDeckBridge.toggle();expect(x.audios[0].pause).toHaveBeenCalled();x.w.RadioDeckBridge.toggle();await flush();x.audios[1].dispatchEvent(new x.w.Event('loadedmetadata'));expect(x.audios[1].currentTime).toBe(125);const slider=x.w.document.getElementById('radioVolume');slider.value='.2';slider.dispatchEvent(new x.w.Event('input'));expect(x.audios[1].volume).toBe(.2);x.d.window.close();});
test('closing panel keeps music; returning to radio stops the MP3',async()=>{const x=setup();x.w.document.getElementById('radioBtn').click();x.w.RadioDeckBridge.select('personal');await flush();x.w.document.getElementById('radioDockClose').click();expect(x.w.RadioDeckBridge.state.playing).toBe(true);x.w.document.querySelector('[data-music-source=radio]').click();await flush();expect(x.audios[0].pause).toHaveBeenCalled();expect(x.audios[0].src).toBe('');expect(x.w.RadioDeckBridge.state.local).toBe(false);x.d.window.close();});
test('failed MP3 playback exposes a retry status and never claims playing',async()=>{const x=setup();x.w.Audio.prototype.play=()=>Promise.reject(Object.assign(new Error('blocked'),{name:'NotAllowedError'}));x.w.RadioDeckBridge.select('personal');await flush();expect(x.w.RadioDeckBridge.state.playing).toBe(false);expect(x.w.document.getElementById('radioDockStatus').dataset.kind).toBe('error');x.d.window.close();});
test('new canvas colors differ by theme and real signal strengthens strokes',()=>{const d=new JSDOM('<html data-theme="dark"></html>',{runScripts:'outside-only'});d.window.eval(fs.readFileSync('src/js/music-atmosphere.js','utf8'));const widths=[],fills=[],ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>{if(k==='lineWidth')widths.push(v);if(k==='fillStyle'&&typeof v==='string')fills.push(v);o[k]=v;return true;}});d.window.MusicAtmosphere.render(ctx,1200,700,1,0,0,0,null);const quiet=Math.max(...widths);widths.length=0;for(let i=0;i<20;i++)d.window.MusicAtmosphere.render(ctx,1200,700,i+2,1,1,1,new Uint8Array(512).fill(255));expect(Math.max(...widths)).toBeGreaterThan(quiet);expect(fills).toContain('#020a10');d.window.document.documentElement.dataset.theme='light';d.window.MusicAtmosphere.render(ctx,1200,700,0,0,0,0,null);expect(fills).toContain('#f4f3ef');d.window.close();});

function atmosphere(photo){const d=new JSDOM('<html data-theme="dark"></html>',{runScripts:'outside-only'});if(photo)d.window.Image=class{constructor(){this.complete=true;this.naturalWidth=photo[0];this.naturalHeight=photo[1];}};d.window.eval(fs.readFileSync('src/js/music-atmosphere.js','utf8'));return d;}
const screens=[[320,568],[390,844],[844,390],[820,1180],[1366,768],[1920,1080],[2560,1080],[3840,2160],[1000,2000],[5120,1440]];
test('photo fills every screen with no gap and keeps its proportions',()=>{const d=atmosphere();for(const [w,h] of screens){const p=d.window.MusicAtmosphere.cover(w,h,1221,690);expect(p.dx).toBeLessThanOrEqual(0);expect(p.dy).toBeLessThanOrEqual(0);expect(p.dx+p.dw).toBeGreaterThanOrEqual(w);expect(p.dy+p.dh).toBeGreaterThanOrEqual(h);expect(p.dw/p.dh).toBeCloseTo(p.sw/p.sh,6);expect(p.sx).toBeGreaterThan(11);expect(p.sy).toBeGreaterThan(11);expect(p.sx+p.sw).toBeLessThan(1221-4);expect(p.sy+p.sh).toBeLessThan(690-4);const beam=p.ox+p.iw*.511;expect(beam).toBeGreaterThan(w*.4);expect(beam).toBeLessThan(w*.6);}d.window.close();});
test('photo is drawn exactly once per frame, never tiled or duplicated',()=>{const d=atmosphere([1221,690]),draws=[],ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),drawImage:(...a)=>draws.push(a)},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>{o[k]=v;return true;}});for(const [w,h] of screens){draws.length=0;d.window.MusicAtmosphere.render(ctx,w,h,1000,.5,.5,.5,null);expect(draws).toHaveLength(1);const [,sx,sy,sw,sh,dx,dy,dw,dh]=draws[0];expect(dx).toBeLessThanOrEqual(0);expect(dy).toBeLessThanOrEqual(0);expect(dx+dw).toBeGreaterThanOrEqual(w);expect(dy+dh).toBeGreaterThanOrEqual(h);expect(sx+sw).toBeLessThan(1221);expect(sy+sh).toBeLessThan(690);}d.window.close();});
