const fs=require('fs'),{JSDOM}=require('jsdom');
function setup(api=true){const d=new JSDOM('<html lang="ru"><head></head><body><button id="radioBtn"><span class="radio-nav-label"></span><span class="radio-nav-state"></span></button><aside id="radioDock" class="open"><div class="radio-dock-top"></div><button id="radioDockClose"></button></aside></body></html>',{url:'https://example.com/',runScripts:'outside-only'}),w=d.window;w.RadioDeckBridge={stop:jest.fn(),externalPlaying:jest.fn()};const players=[];if(api)w.YT={Player:function(id,opts){this.options=opts;this.destroy=jest.fn();this.playVideo=jest.fn();this.getIframe=()=>w.document.createElement('iframe');players.push(this);}};w.eval(fs.readFileSync('src/js/youtube-deck.js','utf8'));return {d,w,players,select:name=>w.document.querySelector('[data-source="'+name+'"]').click()};}
const flush=async()=>{await Promise.resolve();await Promise.resolve();};
test('YouTube is lazy, stops radio, uses requested video and official controls',async()=>{const x=setup();expect(x.players).toHaveLength(0);x.select('youtube');await flush();expect(x.w.RadioDeckBridge.stop).toHaveBeenCalled();const p=x.players[0];expect(p.options.videoId).toBe('cgQMjU_X6sc');expect(p.options.playerVars.controls).toBe(1);p.options.events.onReady({target:p});expect(p.playVideo).toHaveBeenCalled();p.options.events.onStateChange({data:1});expect(x.w.RadioDeckBridge.externalPlaying).toHaveBeenLastCalledWith(true);x.select('radio');expect(p.destroy).toHaveBeenCalled();p.options.events.onStateChange({data:1});expect(x.w.RadioDeckBridge.externalPlaying).toHaveBeenLastCalledWith(false);x.d.window.close();});
test('close destroys video and stale ready callback cannot restart it',async()=>{const x=setup();x.select('youtube');await flush();const p=x.players[0];x.w.document.getElementById('radioDockClose').click();p.options.events.onReady({target:p});expect(p.playVideo).not.toHaveBeenCalled();expect(p.destroy).toHaveBeenCalled();expect(x.w.document.querySelector('.youtube-stage').hidden).toBe(true);x.d.window.close();});
test('error provides link and retry, autoplay restriction does not claim playback',async()=>{const x=setup();x.select('youtube');await flush();const p=x.players[0];p.options.events.onAutoplayBlocked();expect(x.w.document.querySelector('.youtube-status').textContent).toContain('Нажмите');p.options.events.onError({data:101});expect(x.w.document.querySelector('.youtube-status').textContent).toContain('недоступно');expect(x.w.document.querySelector('.youtube-start').hidden).toBe(false);expect(x.w.document.querySelector('.youtube-links a').href).toBe('https://www.youtube.com/watch?v=cgQMjU_X6sc');x.d.window.close();});
test('switch away while API loads cannot create or play a stale video',async()=>{const x=setup(false);x.select('youtube');expect(x.w.document.querySelector('#musicYouTubeAPI')).not.toBeNull();x.select('radio');const ctor=jest.fn();x.w.YT={Player:ctor};x.w.onYouTubeIframeAPIReady();await flush();expect(ctor).not.toHaveBeenCalled();x.d.window.close();});
test('API network error restores a retry instead of remaining loading',async()=>{const x=setup(false);x.select('youtube');x.w.document.querySelector('#musicYouTubeAPI').dispatchEvent(new x.w.Event('error'));await flush();expect(x.w.document.querySelector('.youtube-start').hidden).toBe(false);expect(x.w.document.querySelector('.youtube-status').textContent).toContain('не загрузился');x.d.window.close();});

test('actual radio transport cancels pending stream when YouTube is selected',async()=>{
 const d=new JSDOM('<html lang="en"><head></head><body><button id="radioBtn"></button></body></html>',{url:'https://example.com/',runScripts:'outside-only'}),w=d.window,audios=[];
 w.matchMedia=()=>({matches:false,addEventListener(){}});w.cancelAnimationFrame=()=>{};
 w.Audio=class extends w.EventTarget{constructor(){super();audios.push(this);this.pause=jest.fn();this.load=jest.fn();}play(){return new Promise(()=>{});}removeAttribute(k){if(k==='src')this.src='';}};
 w.eval(fs.readFileSync('src/js/radio-visualizer.js','utf8'));w.YT={Player:function(){this.destroy=jest.fn();}};w.eval(fs.readFileSync('src/js/youtube-deck.js','utf8'));
 w.document.getElementById('radioBtn').click();const pending=w.startRadio();expect(audios).toHaveLength(1);w.document.querySelector('[data-source="youtube"]').click();await pending;await flush();expect(audios[0].pause).toHaveBeenCalled();expect(audios[0].src).toBe('');expect(audios).toHaveLength(1);w.document.querySelector('[data-source="radio"]').click();d.window.close();
});
