/* Strategy worksheet and deterministic risk estimator, intentionally read-only. */
(() => {
 'use strict';
 const host=document.getElementById('strategyDesk');if(!host||!window.TradingRiskEngine)return;
 const en=document.documentElement.lang==='en',t=(ru,eng)=>en?eng:ru;
 const field=(key,label,type='number')=>`<label>${label}<input data-risk="${key}" type="${type}" ${type==='number'?'step="any" min="0"':''} autocomplete="off"></label>`;
 const area=(key,label)=>`<label>${label}<textarea data-plan="${key}" maxlength="5000"></textarea></label>`;
 host.innerHTML=`<div class="wrap"><div class="sec-head"><h2 class="sec-title">${t('Торговый план и риск','Trading plan & risk')}</h2></div>
 <p class="strategy-intro">${t('Контекст → структура → сценарии → риск. Расчёт обновляется при изменении данных. Баланс и спецификации вводятся вручную из терминала; это не подключение к брокеру.','Context → structure → scenarios → risk. Estimates update with your inputs. Enter current account data and specifications from your terminal; this is not a broker connection.')}</p>
 <div class="strategy-grid">
 <article class="strategy-card"><h3><span>01</span>${t('Контекст','Context')}</h3>
 ${area('context',t('События и новости: время, часовой пояс, источник, окно без торговли','Events and news: time, timezone, source, no-trade window'))}
 ${area('trend',t('Старший тренд: инструмент, H4/D1, направление и условие отмены','Higher timeframe: symbol, H4/D1, direction and invalidation'))}
 <label><input type="checkbox" data-check="news">${t('Календарь проверен; сейчас нет моего запрета на вход','Calendar checked; my current entry window is permitted')}</label></article>
 <article class="strategy-card"><h3><span>02</span>${t('Структура','Structure')}</h3>
 ${area('structure',t('Уровни / liquidity / Supply–Demand: цены зон и таймфрейм','Levels / liquidity / Supply–Demand: zone prices and timeframe'))}
 ${area('trigger',t('BOS/CHOCH: какой swing, закрытие какой свечи, подтверждение и invalidation','BOS/CHOCH: which swing, which candle close, confirmation and invalidation'))}
 <p>${t('Отметка BOS/CHOCH сама по себе не подтверждает прибыльность. Запишите однозначное правило, которое можно проверить на истории.','A BOS/CHOCH label does not establish profitability. Define an unambiguous rule that can be tested on historical data.')}</p></article>
 <article class="strategy-card"><h3><span>03</span>${t('Сценарии','Scenarios')}</h3>
 ${area('bullish',t('Bullish: условие входа, подтверждение, отмена','Bullish: entry condition, confirmation, invalidation'))}
 ${area('bearish',t('Bearish: условие входа, подтверждение, отмена','Bearish: entry condition, confirmation, invalidation'))}
 ${area('noTrade',t('Когда пропускаю сделку: новости, спред, отсутствие подтверждения','When I skip: news, spread, missing confirmation'))}
 <label><input type="checkbox" data-check="setup">${t('Условия выбранного сценария выполнены','Selected scenario conditions are met')}</label></article>
 <article class="strategy-card"><h3>${t('Готовые инструменты','Existing tools')}</h3>
 <p><a href="https://www.earnforex.com/metatrader-expert-advisors/Position-Sizer/" target="_blank" rel="noopener">MT5 · Position Sizer</a> — ${t('расчёт лота по стопу, балансу/equity и валюте счёта. Проверяйте на демо у своего брокера.','position sizing from stop, balance/equity and account currency. Validate on your broker’s demo account.')}</p>
 <p><a href="https://www.freqtrade.io/en/stable/strategy-101/" target="_blank" rel="noopener">Crypto · Freqtrade</a> — ${t('каркас для формализованной стратегии, backtest и dry-run. Не готовый прибыльный бот.','framework for coded rules, backtesting and dry-run; not a ready profitable bot.')}</p>
 <p><a href="https://www.tradingview.com/support/solutions/43000529348-how-to-configure-webhook-alerts/" target="_blank" rel="noopener">TradingView · Alerts / webhook</a> — ${t('события для будущей автоматизации. В этом модуле приём webhook и отправка ордеров не подключены.','events for future automation. This module does not receive webhooks or place orders.')}</p>
 <details><summary>${t('Поэтапное внедрение','Rollout steps')}</summary><ol>
 <li>${t('Опишите точные правила BOS/CHOCH и новости-фильтр. Зафиксируйте таймфрейм и источник свечей.','Specify exact BOS/CHOCH and news-filter rules, timeframe and candle source.')}</li>
 <li>${t('Проверьте историю с комиссиями, спредом и проскальзыванием; отдельно период вне обучающей выборки.','Backtest with fees, spread and slippage; reserve an out-of-sample period.')}</li>
 <li>${t('MT5: скачайте Position Sizer с официальной страницы → Файл → Открыть каталог данных → MQL5/Experts. Следуйте инструкции разработчика, сначала демо.','MT5: download Position Sizer from its official page → File → Open Data Folder → MQL5/Experts. Follow the maintainer’s installation guide and start on demo.')}</li>
 <li>${t('Сравните лот и убыток у стопа с терминалом. Для MT5 используйте OrderCalcProfit/OrderCalcMargin; для биржи — актуальные фильтры инструмента.','Compare size and stop loss with the terminal. Use OrderCalcProfit/OrderCalcMargin for MT5 and current symbol filters for exchanges.')}</li>
 <li>${t('Будущий серверный шлюз: свежий баланс, открытый риск, лимиты, проверка дублей, аварийный стоп и журнал действий. Только после demo-тестов подключать исполнение.','Future server gateway: fresh balances, open risk, limits, duplicate protection, kill switch and audit trail. Connect execution only after demo validation.')}</li>
 </ol></details></article>
 <article class="strategy-card strategy-risk"><h3><span>04</span>${t('Риск и размер позиции','Risk & position size')}</h3>
 <div class="strategy-fields">
 <label>${t('Рынок / модель','Market / model')}<select data-meta="market"><option value="spot">Crypto spot (linear)</option><option value="linear">Crypto perpetual (linear)</option><option value="forex">Forex / CFD</option><option value="futures">Exchange futures</option><option value="stocks">Stocks</option><option value="unsupported">Inverse / options</option></select></label>
 <label>${t('Инструмент','Symbol')}<input data-meta="symbol" maxlength="40" placeholder="BTCUSDT / EURUSD"></label>
 <label>${t('Валюта счёта','Account currency')}<input data-meta="currency" maxlength="8" placeholder="USD / EUR / USDT"></label>
 <label>${t('Единица объёма','Volume unit')}<select data-meta="unit"><option>units</option><option>lots</option><option>contracts</option><option>shares</option></select></label>
 <label>${t('База риска','Risk basis')}<select data-risk="basis"><option value="conservative">min(balance, equity)</option><option value="balance">Balance</option><option value="equity">Equity</option></select></label>
 <label>${t('Направление','Direction')}<select data-risk="side"><option value="long">Long</option><option value="short">Short</option></select></label>
 ${field('balance',t('Текущий balance','Current balance'))}${field('equity',t('Текущий equity','Current equity'))}${field('riskPct',t('Риск новой сделки, %','New trade risk, %'))}
 ${field('entry','Entry')}${field('stop','Stop')}${field('target','Target')}
 </div><details open><summary>${t('Лимиты счёта и доступные средства','Account limits and available funds')}</summary>
 <p>${t('Все денежные поля — в валюте счёта. Укажите актуальные нижние границы equity из правил своего счёта: дневную и общую (включая trailing). При отсутствии ограничения явно введите 0. Открытый риск — дополнительный убыток от ТЕКУЩЕГО equity до стопов всех открытых позиций, включая коррелированные. Не повторяйте уже учтённый floating loss.','All money fields use account currency. Enter the current daily and overall equity floors from your account rules, including trailing limits. Explicitly enter 0 if a floor does not apply. Open risk is additional loss from CURRENT equity to all existing stops, including correlated positions. Do not count existing floating loss twice.')}</p>
 <div class="strategy-fields">${field('dailyFloor',t('Дневной equity floor','Daily equity floor'))}${field('totalFloor',t('Общий equity floor','Overall equity floor'))}${field('openRisk',t('Открытый риск до стопов','Additional open risk to stops'))}${field('portfolioPct',t('Предел суммарного риска, %','Portfolio risk cap, %'))}${field('reserve',t('Денежный резерв до лимитов','Cash buffer above floors'))}${field('freeMargin',t('Свободная маржа / доступные деньги','Free margin / available cash'))}</div></details>
 <details open><summary>${t('Спецификация инструмента','Instrument specification')}</summary>
 <p>${t('Tick value LOSS — убыток одного тика на 1 lot/contract/unit в валюте счёта. Forex и кросс-валюты требуют актуальной конвертации; нельзя считать все пары как $10/pip. Для spot: маржа на единицу = цена покупки с конвертацией и комиссией. Для деривативов берите оценку маржи из терминала. Леверидж не уменьшает риск у стопа.','Tick value LOSS is loss per tick per 1 lot/contract/unit in account currency. Forex and cross currencies require current conversion; not every pair is $10/pip. For spot, margin per unit means purchase price converted to account currency plus entry fee. For derivatives, use the terminal margin estimate. Leverage does not reduce stop risk.')}</p>
 <div class="strategy-fields">${field('tickSize','Tick size')}${field('tickValue',t('Tick value LOSS / 1 единицу','Tick value LOSS / 1 volume unit'))}${field('step',t('Шаг объёма','Volume step'))}${field('minQty',t('Минимальный объём','Minimum volume'))}${field('maxQty',t('Максимальный объём','Maximum volume'))}${field('cost',t('Все издержки / единицу (обе стороны)','All-in costs / volume unit (round trip)'))}${field('slippageTicks',t('Дополнительное проскальзывание, тики','Extra slippage allowance, ticks'))}${field('marginPerUnit',t('Маржа / деньги на 1 единицу','Margin / cash per volume unit'))}${field('unitNotional',t('Номинал 1 единицы в валюте счёта','Notional per volume unit in account currency'))}${field('minNotional',t('Мин. номинал в валюте счёта (0 если нет)','Min. notional in account currency (0 if none)'))}</div>
 <p>${t('Издержки включают комиссии, спред (если ещё не учтён в ценах) и ожидаемое финансирование. Не учитывайте один расход дважды.','Include fees, spread if not already reflected in prices, and expected funding. Do not count a cost twice.')}</p></details>
 <label><input type="checkbox" data-check="verified">${t('Я проверил текущие balance/equity, открытые позиции, лимиты и спецификацию в терминале','I verified current balance/equity, open positions, limits and symbol specifications in the terminal')}</label>
 <div class="strategy-result" role="status" aria-live="polite" id="strategyResult"></div>
 <p class="strategy-meta">${t('Оценка по введённым данным, не гарантия максимального убытка: гэп и проскальзывание могут превысить резерв. Запрет здесь не блокирует терминал. План не сохраняется в Supabase; скачайте JSON перед уходом со страницы.','Estimate based on your inputs, not a guaranteed maximum loss: gaps and slippage can exceed the allowance. A blocked plan does not lock your terminal. Plans are not saved to Supabase; download JSON before leaving.')}</p>
 <div class="strategy-actions"><button type="button" class="btn btn-ghost" id="strategyExample">${t('Загрузить учебный пример EURUSD','Load educational EURUSD example')}</button><button type="button" class="btn btn-primary" id="strategyExport">${t('Скачать план JSON','Download plan JSON')}</button></div>
 <p class="strategy-meta" id="strategySource">${t('Источник: ручной ввод. Автосинхронизации с брокером нет.','Source: manual input. No automatic broker sync.')}</p>
 </article></div></div>`;
 const result=host.querySelector('#strategyResult');let verifiedAt=null,demo=false;
 const read=()=>{const p={};host.querySelectorAll('[data-risk]').forEach(el=>p[el.dataset.risk]=el.tagName==='SELECT'?el.value:el.value.trim()===''?NaN:Number(el.value));return p;};
 const messages={missing:t('Заполните все числовые поля; нулевые расходы укажите явно.','Complete every numeric field; enter zero costs explicitly.'),invalid:t('Проверьте положительные цены, баланс, спецификацию и допустимые лимиты.','Check positive prices, balance, specifications and valid limits.'),direction:t('Stop и Target должны соответствовать направлению сделки.','Stop and target must match the trade direction.'),tick:t('Цены должны соответствовать шагу tick size.','Prices must align with tick size.'),limit:t('СТОП: исчерпан дневной, общий или портфельный запас риска.','STOP: daily, overall or portfolio risk capacity is exhausted.'),minimum:t('СТОП: допустимый объём ниже минимума либо не хватает доступной маржи/денег.','STOP: allowed size is below minimum or available margin/cash is insufficient.')};
 const format=n=>n.toLocaleString(en?'en-US':'ru-RU',{maximumFractionDigits:8});
 function snapshot(){const inputs=read(),meta=Object.fromEntries([...host.querySelectorAll('[data-meta]')].map(e=>[e.dataset.meta,e.value.trim()])),notes=Object.fromEntries([...host.querySelectorAll('[data-plan]')].map(e=>[e.dataset.plan,e.value.trim()]));let calc=window.TradingRiskEngine.calculate(inputs);
  if(meta.market==='unsupported')calc={ok:false,code:'unsupported'};
  if(meta.market==='spot'&&inputs.side==='short')calc={ok:false,code:'spotShort'};
  const checked=verifiedAt&&Date.now()-Date.parse(verifiedAt)<300000&&[...host.querySelectorAll('[data-check]')].every(e=>e.checked),complete=Object.values(notes).every(Boolean)&&meta.symbol&&meta.currency;
  return {version:1,createdAt:new Date().toISOString(),source:demo?'educational example':'manual terminal snapshot',verifiedAt,meta,notes,inputs,checks:Object.fromEntries([...host.querySelectorAll('[data-check]')].map(e=>[e.dataset.check,e.checked])),estimate:calc,status:calc.ok&&calc.reward>0&&checked&&complete&&!demo?'review-ready':'draft',execution:'disabled'};
 }
 function render(){const s=snapshot(),r=s.estimate;result.dataset.ok=String(r.ok);if(!r.ok){result.textContent=messages[r.code]||(r.code==='spotShort'?t('Spot Short не поддерживается: продажа заёмных активов требует отдельной модели.','Spot shorts are not supported; borrowed assets need a separate model.'):t('Inverse-контракты и опционы требуют нелинейной модели; расчёт заблокирован.','Inverse contracts and options require a nonlinear model; calculation blocked.'));return;}
  result.textContent=[s.status==='review-ready'?t('ПЛАН ГОТОВ К РУЧНОЙ ПРОВЕРКЕ — не торговый сигнал','PLAN READY FOR MANUAL REVIEW — not a trade signal'):t('ЧЕРНОВИК — заполните 01–03 и подтвердите данные (проверка действует 5 минут)','DRAFT — complete 01–03 and verify data (valid for 5 minutes)'),`${t('Объём','Size')}: ${format(r.units)} ${s.meta.unit}`,`${t('Расчётный убыток у стопа с издержками','Estimated stop loss including costs')}: ${format(r.risk)} ${s.meta.currency}`,`${t('Запрошенный риск / доступный бюджет','Requested risk / available budget')}: ${format(r.requested)} / ${format(r.budget)}`,`${t('Результат у цели после издержек','Target result after costs')}: ${format(r.reward)} · R:R 1:${format(r.rr)}`,`${t('Маржа / номинал','Margin / notional')}: ${format(r.margin)} / ${format(r.notional)}`,r.limited?t('Объём уменьшен лимитами риска, маржи или спецификации.','Size reduced by risk, margin or symbol limits.'):t('Объём округлён вниз по шагу.','Size rounded down to volume step.'),r.reward<=0?t('ВНИМАНИЕ: ожидаемые издержки перекрывают движение к цели.','CAUTION: estimated costs exceed the target move.'):''].filter(Boolean).join('\n');
 }
 host.addEventListener('input',e=>{if(e.target.matches('[data-risk],[data-meta]')){host.querySelector('[data-check="verified"]').checked=false;verifiedAt=null;}if(e.target.matches('[data-check="verified"]'))verifiedAt=e.target.checked?new Date().toISOString():null;render();});
 host.querySelector('#strategyExample').addEventListener('click',()=>{demo=true;verifiedAt=null;const example={balance:10000,equity:9800,basis:'conservative',side:'long',riskPct:.5,entry:1.1,stop:1.098,target:1.104,tickSize:.00001,tickValue:1,step:.01,minQty:.01,maxQty:100,dailyFloor:9500,totalFloor:9000,openRisk:30,portfolioPct:1,reserve:20,cost:7,slippageTicks:2,marginPerUnit:3666.67,freeMargin:5000,unitNotional:110000,minNotional:0};for(const[k,v]of Object.entries(example))host.querySelector(`[data-risk="${k}"]`).value=v;for(const[k,v]of Object.entries({market:'forex',symbol:'EURUSD — DEMO',currency:'USD',unit:'lots'}))host.querySelector(`[data-meta="${k}"]`).value=v;host.querySelectorAll('[data-check]').forEach(e=>e.checked=false);host.querySelector('#strategySource').textContent=t('УЧЕБНЫЕ ДАННЫЕ, не ваш счёт. Перезагрузите страницу для нового реального плана.','EDUCATIONAL DATA, not your account. Reload for a new real plan.');render();});
 host.querySelector('#strategyExport').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='trading-plan-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});render();
 const freshnessTimer=setInterval(render,30000);window.addEventListener('pagehide',()=>clearInterval(freshnessTimer),{once:true});
})();
